variable "env" {
  description = "Environment slug (dev, staging, prod)."
  type        = string
}

variable "location" {
  description = "Azure region."
  type        = string
}

variable "resource_group_name" {
  description = "Resource group that holds the PG server + private DNS zone."
  type        = string
}

variable "vnet_id" {
  description = "VNet resource ID. Used for the private-DNS-zone-to-VNet link."
  type        = string
}

variable "delegated_subnet_id" {
  description = "Subnet resource ID. Must be delegated to Microsoft.DBforPostgreSQL/flexibleServers (M1 sets this up on the 'pg' subnet)."
  type        = string
}

variable "admin_username" {
  description = "PostgreSQL admin login name (e.g. psadmin)."
  type        = string
}

variable "admin_password" {
  description = "PostgreSQL admin password. Generated by random_password at env level; persisted to Key Vault."
  type        = string
  sensitive   = true
}

variable "sku_name" {
  description = "PG Flex SKU. Format: <Tier>_<Family>_<Size>. Examples: B_Standard_B1ms (Burstable 1vC/2GB), GP_Standard_D2ds_v5 (General Purpose 2vC/8GB)."
  type        = string
}

variable "storage_mb" {
  description = "Storage size in MB. 32768 = 32 GB (dev); 65536 = 64 GB (staging)."
  type        = number
}

variable "backup_retention_days" {
  description = "Backup retention (7-35 days). Dev: 7. Staging: 35."
  type        = number
  default     = 7

  validation {
    condition     = var.backup_retention_days >= 7 && var.backup_retention_days <= 35
    error_message = "backup_retention_days must be between 7 and 35."
  }
}

variable "geo_redundant_backup_enabled" {
  description = "Enable geo-redundant backup. Dev: false. Staging: true."
  type        = bool
  default     = false
}

variable "pgbouncer_enabled" {
  description = "Enable built-in PgBouncer (transaction pool mode). Only supported on Standard SKUs, NOT Burstable. Dev (B1ms): false. Staging (D2ds_v5): true."
  type        = bool
  default     = false
}

variable "database_name" {
  description = "Initial database name inside the server. Matches Odoo's db_filter regex ^posterra_(dev|staging|prod)$."
  type        = string
}

variable "tags" {
  description = "Tags applied to every resource in this module."
  type        = map(string)
  default     = {}
}
