from . import saas_app
from . import res_partner
from . import hha_provider
from . import hha_scope_group
from . import hha_scope_group_match_field
from . import dashboard_page
from . import dashboard_page_filter
from . import dashboard_filter_dependency
from . import dashboard_widget
from . import dashboard_widget_scope_option
from . import dashboard_page_section
from . import dashboard_filter_state
from . import res_config_settings
from . import dashboard_builder_ext
from . import dashboard_page_badge
from . import dashboard_page_template
from . import geo_zip_centroid