import React, { createContext, useContext, useState, useEffect, useRef, useCallback } from 'react'

const TokenContext = createContext(null)

/**
 * How far before expiry (in ms) to proactively refresh.
 * 5 minutes before the 1-hour TTL → refresh at ~55 min.
 */
const REFRESH_MARGIN_MS = 5 * 60 * 1000

/**
 * TokenProvider
 *
 * Manages the JWT access token lifecycle:
 *   1. Proactive refresh — schedules a timer to silently fetch a new token
 *      before the current one expires.
 *   2. 401 safety net   — exposes refreshToken() so apiFetch can retry on 401.
 */
export function TokenProvider({ children, initialToken, appKey, apiBase }) {
  const [token, setToken] = useState(initialToken || '')
  const timerRef = useRef(null)
  const refreshingRef = useRef(null) // dedup concurrent refresh calls

  /** Fetch a fresh token from the session-refresh endpoint. */
  const refreshToken = useCallback(async () => {
    // Dedup: if a refresh is already in flight, reuse its promise
    if (refreshingRef.current) return refreshingRef.current

    const promise = (async () => {
      try {
        const params = appKey ? `?app_key=${encodeURIComponent(appKey)}` : ''
        const res = await fetch(`${apiBase}/auth/session-refresh${params}`, {
          method: 'POST',
          credentials: 'same-origin', // send the Odoo session cookie
          headers: { 'Content-Type': 'application/json' },
        })
        if (!res.ok) {
          // Session itself expired — full page reload to trigger login
          if (res.status === 401 || res.status === 303) {
            window.location.reload()
            return null
          }
          throw new Error(`Token refresh failed: ${res.status}`)
        }
        const data = await res.json()
        const newToken = data.access_token
        const expiresIn = data.expires_in || 3600
        setToken(newToken)
        scheduleRefresh(expiresIn)
        return newToken
      } catch (err) {
        console.error('[TokenManager] refresh error:', err)
        return null
      } finally {
        refreshingRef.current = null
      }
    })()

    refreshingRef.current = promise
    return promise
  }, [appKey, apiBase]) // eslint-disable-line react-hooks/exhaustive-deps

  /** Schedule the next proactive refresh. */
  const scheduleRefresh = useCallback((expiresInSec) => {
    if (timerRef.current) clearTimeout(timerRef.current)
    const delayMs = Math.max((expiresInSec * 1000) - REFRESH_MARGIN_MS, 30_000)
    timerRef.current = setTimeout(() => { refreshToken() }, delayMs)
  }, [refreshToken])

  // On mount: schedule the first proactive refresh based on the 1h TTL.
  // The initial token was just generated by portal.py, so full TTL applies.
  useEffect(() => {
    if (token) {
      scheduleRefresh(3600) // ACCESS_TOKEN_TTL
    }
    return () => { if (timerRef.current) clearTimeout(timerRef.current) }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  // Handle tab visibility: refresh immediately when tab becomes visible
  // after being backgrounded (browser may have throttled the timer).
  useEffect(() => {
    const onVisible = () => {
      if (document.visibilityState === 'visible') {
        refreshToken()
      }
    }
    document.addEventListener('visibilitychange', onVisible)
    return () => document.removeEventListener('visibilitychange', onVisible)
  }, [refreshToken])

  return (
    <TokenContext.Provider value={{ token, refreshToken }}>
      {children}
    </TokenContext.Provider>
  )
}

/** Hook to access the current token and refresh function. */
export const useToken = () => {
  const ctx = useContext(TokenContext)
  if (!ctx) throw new Error('useToken must be used inside <TokenProvider>')
  return ctx
}
