# -*- coding: utf-8 -*-

import json
import logging

from odoo import api, fields, models

_logger = logging.getLogger(__name__)


class DashboardWidgetDefinition(models.Model):
    _name = 'dashboard.widget.definition'
    _description = 'Widget Definition (Library)'
    _inherit = ['dashboard.widget.action.mixin']
    _order = 'category, name'

    # ── Identity ─────────────────────────────────────────────────────────────
    name           = fields.Char(required=True, string='Widget Name')
    description    = fields.Text(string='Description')
    category       = fields.Selection([
        ('kpi',         'KPI Cards'),
        ('chart',       'Charts'),
        ('table',       'Tables'),
        ('comparison',  'Comparisons'),
        ('profile',     'Profiles'),
        ('insight',     'Insights'),
    ], default='chart')
    preview_image  = fields.Binary(attachment=True, string='Preview Thumbnail')
    is_active      = fields.Boolean(default=True)

    # ── Chart / Display ──────────────────────────────────────────────────────
    chart_type = fields.Selection([
        ('bar',           'Bar'),
        ('line',          'Line'),
        ('pie',           'Pie'),
        ('donut',         'Donut'),
        ('gauge',         'Gauge'),
        ('radar',         'Radar'),
        ('kpi',           'KPI Card'),
        ('status_kpi',    'Status KPI'),
        ('table',         'Data Table'),
        ('scatter',       'Scatter'),
        ('heatmap',       'Heatmap'),
        ('battle_card',   'Battle Card'),
        ('insight_panel', 'Insight Panel'),
        ('gauge_kpi',     'Gauge + KPI'),
        ('map',           'Map'),
    ], required=True, default='bar')
    chart_height      = fields.Integer(default=350, string='Default Height (px)')
    color_palette     = fields.Selection([
        ('default',     'Default'),
        ('healthcare',  'Healthcare'),
        ('ocean',       'Ocean'),
        ('warm',        'Warm'),
        ('mono',        'Monochrome'),
        ('custom',      'Custom'),
    ], default='healthcare')
    color_custom_json = fields.Char(string='Custom Colors (JSON)')
    default_col_span  = fields.Selection([
        ('3',  '25%'),
        ('4',  '33%'),
        ('6',  '50%'),
        ('8',  '67%'),
        ('12', '100%'),
    ], default='6', string='Default Width (preset)')
    default_width_pct = fields.Integer(
        default=0, string='Default Width (%)',
        help='Custom default width as a percentage (1–100). '
             'When set, overrides the preset Width.')
    default_row_span = fields.Integer(
        default=1, string='Default Row Span',
        help='How many grid rows this widget spans by default. '
             'Use 2+ for tall widgets like maps.')

    # ── Data Source ──────────────────────────────────────────────────────────
    data_mode = fields.Selection([
        ('visual',     'Visual Builder'),
        ('custom_sql', 'Custom SQL'),
    ], default='visual', string='Data Source Mode')

    # Custom SQL mode: raw query
    query_sql     = fields.Text(
        string='SQL Query',
        help='SELECT only. Use %(param)s for filter values.')
    schema_source_id = fields.Many2one(
        'dashboard.schema.source', string='Schema Source',
        ondelete='set null',
        help='MV or table this widget queries. Used for {where_clause} generation.')
    x_column      = fields.Char(string='X / Label Column')
    y_columns     = fields.Char(
        string='Y / Value Column(s)',
        help='Comma-separated result column names')
    series_column = fields.Char(string='Series Column')

    # Generated SQL (for visual mode)
    generated_sql = fields.Text(
        string='Generated SQL (read-only)',
        help='Auto-generated by QueryBuilder from builder_config. '
             'Stored so the widget instance can use it directly.')

    # ── KPI-specific fields ──────────────────────────────────────────────────
    kpi_format = fields.Selection([
        ('number',   'Number'),
        ('currency', 'Currency'),
        ('percent',  'Percent'),
        ('decimal',  'Decimal'),
    ], default='number')
    kpi_prefix = fields.Char()
    kpi_suffix = fields.Char()

    # ── Gauge fields ─────────────────────────────────────────────────────────
    gauge_min        = fields.Float(default=0)
    gauge_max        = fields.Float(default=100)
    gauge_color_mode = fields.Selection([
        ('single',        'Single'),
        ('traffic_light', 'Traffic Light'),
    ], default='single')

    # ── Visual Config (chart-specific flags from React builder) ─────────────
    visual_config = fields.Text(
        string='Visual Config',
        help='JSON object with chart-specific visual flags from the builder.\n'
             'Example: {"orientation": "horizontal", "stack": true}')

    # ── Bar chart options ────────────────────────────────────────────────────
    bar_stack = fields.Boolean(
        string='Stack Bars', default=False,
        help='Stack bar series on top of each other instead of side-by-side.')

    # ── Advanced ─────────────────────────────────────────────────────────────
    echart_override = fields.Text(string='ECharts Override (JSON)')

    # ── Tracking ─────────────────────────────────────────────────────────────
    instance_count = fields.Integer(
        compute='_compute_instance_count', string='Times Used')

    @api.depends()
    def _compute_instance_count(self):
        """Count how many dashboard.widget instances reference this definition.
        Uses a try/except because dashboard.widget may not exist in this module."""
        for rec in self:
            try:
                Widget = self.env['dashboard.widget']
                rec.instance_count = Widget.search_count(
                    [('definition_id', '=', rec.id)])
            except KeyError:
                # dashboard.widget not registered (consuming module not installed)
                rec.instance_count = 0

    def get_effective_sql(self):
        """Returns the SQL to use: generated_sql for visual mode, query_sql for custom."""
        self.ensure_one()
        if self.data_mode == 'custom_sql':
            return self.query_sql
        return self.generated_sql

    def action_regenerate_sql(self):
        """Re-run QueryBuilder on builder_config to update generated_sql."""
        self.ensure_one()
        from ..services.query_builder import QueryBuilder
        qb = QueryBuilder(self.env)
        config = json.loads(self.builder_config or '{}')
        self.generated_sql = qb.build_select_query(config)
